var mongoose = require('mongoose');

var UserSchema = new mongoose.Schema({
    facebook_id: { type: String, unique: true },
    name: { type: String },
    image_url: { type: String },
    age_range: { type: String },
    email: { type: String },
    gender: { type: String },
    lat: { type: Number, default: 0 },
    lon: { type: Number, default: 0 },

    seeking: { type: String },
    country: { type: String },
    zipcode: { type: Number },
    birthday: { type: Date },
    ethnicity: { type: String },
    occupation: { type: String },
    martial_status: { type: String },
    children: { type: String },
    education: { type: String },
    faith: { type: String },
    smoke: { type: String },
    drink: { type: String },
    height: { type: String },
    body: { type: String },
    animal: { type: String },
    age_preference: { type: Number },
    dining: { type: String },
    coffee_tea: { type: String },
    cooking: { type: String },
    shopping: { type: String },
    movies: { type: String },
    television: { type: String },
    music: { type: String },
    games: { type: String },
    fishing: { type: String },
    camping: { type: String },
    travel: { type: String },
    museums: { type: String },
    theatres: { type: String },
    art: { type: String },
    anime: { type: String },
    photography: { type: String },
    gardening: { type: String },
    crafts: { type: String },
    computers: { type: String },
    technology: { type: String },
    karoke: { type: String },
    books: { type: String },
    writing: { type: String },
    cars: { type: String },
    coding: { type: String },
    walking: { type: String },
    hiking: { type: String },
    running: { type: String },
    cycling: { type: String },
    dancing: { type: String },
    swimming: { type: String },
    tennis: { type: String },
    bowling: { type: String },
    skiing: { type: String },
    golf: { type: String },
    martial_arts: { type: String },
    motorsports: { type: String },
    baseball: { type: String },
    basketball: { type: String },
    football: { type: String },
    hockey: { type: String },
    aerobics: { type: String },
    weights: { type: String },
    rock_climing: { type: String },
    soccer: { type: String },
    surfing: { type: String },
    table_tennis: { type: String },
    volleyball: { type: String },
    yoga_pilates: { type: String },
    badminton: { type: String },
    snowboarding: { type: String },
    languages: { type: String },
}, { timestamps: true });

mongoose.model('User', UserSchema);
